const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{"content-type":"application/json; charset=utf-8"}});
const cors=r=>{r.headers.set("Access-Control-Allow-Origin","*");r.headers.set("Access-Control-Allow-Headers","Content-Type, Authorization");r.headers.set("Access-Control-Allow-Methods","GET, POST, OPTIONS");return r};
function slugify(t){return t.trim().toLowerCase().replace(/[^\u0600-\u06FFa-z0-9]+/g,"-").replace(/^-+|-+$/g,"")||crypto.randomUUID()}
function isAdmin(req,env){return (req.headers.get("Authorization")||"")===`Bearer ${env.ADMIN_PASSWORD}`}
export default {async fetch(request,env){if(request.method==="OPTIONS")return cors(new Response(null,{status:204}));const url=new URL(request.url);try{
if(url.pathname==="/api/categories"&&request.method==="GET"){const {results}=await env.DB.prepare("SELECT id,name,slug,icon FROM categories ORDER BY sort_order,name").all();return cors(json(results))}
if(url.pathname==="/api/resources"&&request.method==="GET"){const q=(url.searchParams.get("q")||"").trim(),cat=url.searchParams.get("category")||"";let sql=`SELECT r.id,r.title,r.slug,r.description,r.file_url,r.file_name,r.file_type,r.keywords,r.version,r.downloads,r.created_at,r.updated_at,c.name category_name,c.slug category_slug,c.icon FROM resources r LEFT JOIN categories c ON c.id=r.category_id WHERE r.status='published'`;const b=[];if(q){sql+=" AND (r.title LIKE ? OR r.description LIKE ? OR r.keywords LIKE ?)";const x=`%${q}%`;b.push(x,x,x)}if(cat){sql+=" AND c.slug = ?";b.push(cat)}sql+=" ORDER BY r.updated_at DESC LIMIT 100";const {results}=await env.DB.prepare(sql).bind(...b).all();return cors(json(results))}
if(url.pathname.startsWith("/api/download/")&&request.method==="GET"){const id=Number(url.pathname.split("/").pop());const item=await env.DB.prepare("SELECT file_url FROM resources WHERE id=? AND status='published'").bind(id).first();if(!item?.file_url)return new Response("File link not found",{status:404});await env.DB.prepare("UPDATE resources SET downloads=downloads+1 WHERE id=?").bind(id).run();return Response.redirect(item.file_url,302)}
if(url.pathname==="/api/admin/resources"&&request.method==="POST"){if(!isAdmin(request,env))return cors(json({error:"Unauthorized"},401));const body=await request.json(),title=String(body.title||"").trim(),fileUrl=String(body.file_url||"").trim();if(!title||!fileUrl)return cors(json({error:"اسم المورد ورابط الملف مطلوبان"},400));const slug=slugify(title)+"-"+Date.now();const r=await env.DB.prepare(`INSERT INTO resources(title,slug,description,category_id,file_url,file_name,file_type,keywords,version,status) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(title,slug,body.description||"",body.category_id||null,fileUrl,body.file_name||"",body.file_type||"",body.keywords||"",body.version||"1.0",body.status||"published").run();return cors(json({ok:true,id:r.meta.last_row_id},201))}
return env.ASSETS.fetch(request)}catch(e){return cors(json({error:"Server error",message:e.message},500))}}};
